// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_9myDInlCbRaC1oNwsB3q3q4h_r_yH8',
    appId: '1:872067306299:web:2d4d93078e77fa9275dd1e',
    messagingSenderId: '872067306299',
    projectId: 'weddinger820',
    authDomain: 'weddinger820.firebaseapp.com',
    storageBucket: 'weddinger820.appspot.com',
    measurementId: 'G-ZNH9BP8VRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG__jcc7ASFHm6NdLKzRWz3uCWtvdKQmk',
    appId: '1:872067306299:android:2158320e15d671a775dd1e',
    messagingSenderId: '872067306299',
    projectId: 'weddinger820',
    storageBucket: 'weddinger820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRAo4dtWa5iV7jgqMhbCE1Py5JwvNQAI',
    appId: '1:872067306299:ios:9c6200d4df14f86275dd1e',
    messagingSenderId: '872067306299',
    projectId: 'weddinger820',
    storageBucket: 'weddinger820.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtRAo4dtWa5iV7jgqMhbCE1Py5JwvNQAI',
    appId: '1:872067306299:ios:9c6200d4df14f86275dd1e',
    messagingSenderId: '872067306299',
    projectId: 'weddinger820',
    storageBucket: 'weddinger820.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB_9myDInlCbRaC1oNwsB3q3q4h_r_yH8',
    appId: '1:872067306299:web:d1adeed2f23f58ba75dd1e',
    messagingSenderId: '872067306299',
    projectId: 'weddinger820',
    authDomain: 'weddinger820.firebaseapp.com',
    storageBucket: 'weddinger820.appspot.com',
    measurementId: 'G-35B2GLB676',
  );
}
